language: node_js
node_js:
  - stable

script: echo "We don't have tests yet :("

before_deploy:
  - sh package.sh

deploy:
  - provider: releases
    skip_cleanup: true
    name: "$TRAVIS_TAG"
    api_key:
      secure: VrMqW2eGIk1OyaS7mRNRus3/EOBUEOtaBWXn0/alEfqx26ul/JjLpD272qjwSsb9P94WGwILqBZGcvnw5HcdVOzZHAgCaKA5X40u3Y8xQTzj6dKj9hKVcQmZoG5neKu322XQ0Paez5wl/9FsGRTQtt6m4xL/4B2yRBvCdW0eR+zqBOVQLMNJ+auAaOBOd+LmzmnodCxf/bVj0qHnY+1/arfa8gUytUM6o9RBjecz/KlPkwfHzVgwoocusWOxZzSwxsp9zXM7rYLhqa3ZbS1cmWYUc1nXkSrypIQex/y/fecy9Gv6Oi3Pe20Wu9/R/+2khphcFrx1ku196fl6/8fLDXoHfGF8zNiEhvcfHluUR5IT4b5GtyWEe4GwyvtoV0E8AIJsV8B8M2THvqAY2uX6wJEgzDqQx0/AGwnDiWQDzx/XFqcczHOhQNhthHbQz71QxYrr5GMKCQjyOZQwqH6H62DMLCx5Dh8c/XzKZdeLlsWiqrC/tVObshCPDjInoz8Kzf0/XYvoVts+20IhXOsa+3MVpkdMoElXL8rJXsyC/vdmtByr4XUfAMLmuHDVF/VOY+maIaI/fiZ/mzWHVkiq7DoH6sojExiJtrcjW2JGkW+RBRQgQgClvB6kV6GC8iFmnrB8GXBLi2UkENkVzwpNodrslNGSmDmnXLAoydYoOVs=
    file: dist/POS.js
    on:
      tags: true
      repo: TransbankDevelopers/transbank-pos-sdk-web-serial
  - provider: npm
    skip_cleanup: true
    email: transbankdevelopers@continuum.cl
    api_key:
      secure: Ac72wnf865My0/hPxZXqd6foqiK7LUap6k7GlAkjfhl/NBh7T2feyeFcpgWCHVWm4s3JQoV8wSmLKUz3+hz1hgHRtz7JnY/5VU/NIuuMjXa7zvXkecYDCi8hpxtlFLwhexr3vS6/Y5n+LZBAyoMTK3IrCKRhlsucTQn/nw7dpKwLQcFSocsaX4dFp2o5cY2zfr42iKJlQquUApTU6kU5cPFoq6mfKwQT7/O1UA3NOJkQWx+Xj/v+A1lPtn/hc8CTuAsEN1pUV9ucBK6/QN9BpkHo013UBNbTfJfSUH8dHfAP7OfcD0OQSiX1wnnG3JYE0NonUZp+GhzYEz5XBAUS/6nJJ2TRyw5QoVdnIKzYw19Np9hOmaG9/gjqKyve5SdNwCkurufAz5ubYQbxI+KtCkkJ1T3Q0EpGxzpmW/9xQx/vRpZEWhev0Xk0yjKg6/hVI6v2jf7wYo3k2K9AGDWD+xXmAysVKty8Vc/PkEqjhb1Jsm5h0Z0SKj6eqNChTwnLfWl/9zxsKRuDKKV0CoSdDJ+bohlYUTYuAtlu3TylxNlEor8FDXz3NVTnHZjQT9L3EKwkaxIvXLt6/mn4a/QTiA0kh/KvpJ4zCxHCkzTSskKxo8wLeUJOcQ0mmmMgojxpw/kmS+aU60Nx3L0I5KNYLwV/A59UOkcXNYwsLSop59A=
    on:
      tags: true
      repo: TransbankDevelopers/transbank-pos-sdk-web-serial